spring:
  application:
    name: hhplus
  profiles:
    active: local
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.timezone.default_storage: NORMALIZE_UTC
      hibernate.jdbc.time_zone: UTC

io:
  admin:
    fcfs: 10

#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:ddl.sql
#      data-locations: classpath:test.sql
---
spring.config.activate.on-profile: local

spring:
  datasource:
    name: HangHaePlusDataSource
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 3
      connection-timeout: 10000
      max-lifetime: 60000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hhplus?characterEncoding=UTF-8&serverTimezone=UTC
    username: application
    password: application

  data:
    redis:
      host: localhost
      port: 6379
      password: root
      timeout: 5m
#
#  data:
#    redis:
#      cluster:
#        nodes:
#          - redis-7001:7001
#          - redis-7002:7002
#          - redis-7003:7003
#          - redis-7004:7004
#          - redis-7005:7005
#          - redis-7006:7006
#      timeout: 2000

---
spring.config.activate.on-profile: test

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none  # 테스트 환경에서는 매번 테이블을 새로 생성
    show-sql: true